name: mibook
description: "Project that works as a Reading Manager for avid readers"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0
  get_it: ^8.0.2
  injectable: ^2.5.0
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  build_runner: ^2.4.13
  auto_route: ^9.2.2
  auto_route_generator: ^9.0.0
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  freezed_annotation: ^3.0.0
  encrypted_shared_preferences: ^3.0.1
  flutter_bloc: ^8.1.6
  mockito: ^5.4.6
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  test: ^1.25.2
  freezed: ^3.0.3

targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
